name: Daily Sync Job

on:
  # schedule:
  #   - cron: '21 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install: true 

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run script
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          MONDAY_API_KEY: ${{ secrets.MONDAY_API_KEY }}
          MONDAY_BOARD_ID: ${{ secrets.MONDAY_BOARD_ID }}
        run: uv run src/main.py

      - name: Commit watermark
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .state/last_run.json
          git diff --staged --quiet || git commit -m "chore: update watermark [skip ci]"
          git push origin main