version: 2
updates:
  # 1. Update Python dependencies via uv
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"

    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"